### ISSUE TITLE
Core300S > change_fan_speed > manual mode validation

### ISSUE THREAD

**Issue by digital-cowboy-91** [webdjoe/pyvesync#107]
In **vesyncfan.py** line **673** you are testing if current mode is **manual** while triggering fan speed change, which results in two requests to achieve  that change. Is that necessary? If I want to change the speed, obviously I want to change the fan to manual mode too, so when I've commented this condition and added **'mode': 'manual',** to line **713**, the purifier starts behave as expected.

**Comment by webdjoe** [comment]
Thanks for pointing that out. That makes perfect sense. I'll include it on the next PR

**Comment by webdjoe** [comment]
Fixed, if you wouldn't mind testing - https://github.com/webdjoe/pyvesync/tree/air-refactor

**Comment by digital-cowboy-91** [comment]
The payload seems to be correct, am able to control the Core300S as expected, **BUT only until restart** of environment. If the **device** is **in manual mode** and environment restarts, the device **does not reload**. If the **device is in auto mode**, it **reloads** properly.

The issue might not be related to this module. So if it is not, feel free to close it as payload seems to be correct.

```
2022-03-09 23:29:03 ERROR (MainThread) [homeassistant.components.fan] Error while setting up vesync platform for fan
Traceback (most recent call last):
  File "/home/pticon/core/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/home/pticon/core/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/home/pticon/core/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/pticon/core/homeassistant/helpers/entity.py", line 750, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/pticon/core/homeassistant/helpers/entity.py", line 507, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/pticon/core/homeassistant/helpers/entity.py", line 542, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/home/pticon/core/homeassistant/components/fan/__init__.py", line 475, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/home/pticon/core/homeassistant/components/fan/__init__.py", line 389, in speed
    if (percentage := self.percentage) is None:
  File "/home/pticon/core/homeassistant/components/vesync/fan.py", line 91, in percentage
    and (current_level := self.smartfan.fan_level) is not None
  File "/home/pticon/core/venv/lib/python3.8/site-packages/pyvesync/vesyncfan.py", line 497, in fan_level
    if self.speed.isnumeric():
AttributeError: 'int' object has no attribute 'isnumeric'
```

**Comment by webdjoe** [comment]
Just pushed a fix, should work now

**Comment by digital-cowboy-91** [comment]
Log is clean, work as expected. No issues after restart.

**Edit:** 23 minutes after test following issue pop up
```
2022-03-10 16:43:07 WARNING (SyncWorker_2) [pyvesync.helpers] HTTPSConnectionPool(host='smartapi.vesync.com', port=443): Read timed out. (read timeout=5)
2022-03-10 16:43:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for fan.air_purifier fails
Traceback (most recent call last):
  File "/home/pticon/core/homeassistant/helpers/entity.py", line 489, in async_update_ha_state
    await self.async_device_update()
  File "/home/pticon/core/homeassistant/helpers/entity.py", line 693, in async_device_update
    raise exc
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pticon/core/homeassistant/components/vesync/common.py", line 78, in update
    self.device.update()
  File "/home/pticon/core/venv/lib/python3.8/site-packages/pyvesync/vesyncfan.py", line 235, in update
    self.get_details()
  File "/home/pticon/core/venv/lib/python3.8/site-packages/pyvesync/vesyncfan.py", line 216, in get_details
    outer_result = r.get('result', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by webdjoe** [comment]
Does this happen intermittently and it works otherwise?

**Comment by digital-cowboy-91** [comment]
Basically yes. I can't reproduce it today, so might be an issue on my side.

**Comment by webdjoe** [comment]
No, I think VeSync is rate limiting. I'll just adjust for so it doesn't pop an error when it happens intermittently

**Comment by webdjoe** [comment]
@pticon91 Just pushed a fix can you verify no error is raiised?

**Comment by digital-cowboy-91** [comment]
Sorry for delay. I let it run for few hours and time to time changed values. Logs seems to be clean. No Issue spotted.
