### ISSUE TITLE
Exception error not caught

### ISSUE THREAD

**Issue by borpin** [webdjoe/pyvesync#127]
I am seeing this error in the Home Assistant logs - using V2.0.0
```
2022-04-02 12:16:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.study_hum_auto_mode fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vesync2/common.py", line 124, in update
    self.device.update()
  File "/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py", line 965, in update
    self.get_details()
  File "/usr/local/lib/python3.9/site-packages/pyvesync/vesyncfan.py", line 946, in get_details
    outer_result = r.get('result', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

I think there needs to be an else condition.

https://github.com/webdjoe/pyvesync/blob/c41eb8a77e68cc357f558e4fa413e42f9ba68658/src/pyvesync/vesyncfan.py#L944-L948

**Comment by webdjoe** [comment]
Fixed in #129 published to pypi
