### ISSUE TITLE
IndexError: list index out of range Still Occurs On Firmware 2.125 on a Voltson 7A Switch

### ISSUE THREAD

**Issue by jcefoli** [webdjoe/pyvesync#132]
I am experiencing a similar issues to #131 with a Voltson 7A model ESW01-USA. I tested the fixes in pyvesync 2.0.2 with my newer Voltson plugs (firmware 1.1.30) and can confirm they work just fine. But I have an older Voltson plug (that looks like it's the same hardware model) but has a strange firmware version (2.125). When I used the library to print the device type, it is `wifi-switch-1.3` instead of `ESW01-USA` (the outlets with this device type work just fine). The state of this outlet is correctly shown when I print `manager.outlets`

I know this library is used in Home Assistant, so the behavior there is that it seems to work when the plug is toggled on, but I cannot toggle it off, and when the plug is powered off, it incorrectly reports the last known power usage without clearing it.

These stack traces are from Home Assistant, but it looks like the error is similar to what was fixed in #131. Is there a way to fall back to the old integer reporting just for this firmware, or catch the exception and try the old way?

```IndexError: list index out of range
2022-04-20 00:57:25 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.etekcity_plug_energy_use_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vesync/sensor.py", line 149, in update
    self.smartplug.update()
  File "/usr/local/lib/python3.9/site-packages/pyvesync/vesyncoutlet.py", line 69, in update
    self.get_details()
  File "/usr/local/lib/python3.9/site-packages/pyvesync/vesyncoutlet.py", line 175, in get_details
    power = round(float(Helpers.calculate_hex(power)), 2)
  File "/usr/local/lib/python3.9/site-packages/pyvesync/helpers.py", line 139, in calculate_hex
    converted_hex = (int(hex_conv[0], 16) + int(hex_conv[1], 16)) / 8192
IndexError: list index out of range
```

Interesting: while playing with the library from my python CLI, it seems to be getting the status correctly. Maybe this issue is in Home Assistant. Go ahead and close this if it's not a library issue.

**Comment by webdjoe** [comment]
This should be fixed in #131
