### ISSUE TITLE
Add support for Levoit Dual 200 (LUH-D301S-WEU)

### ISSUE THREAD

**Issue by MickL** [webdjoe/pyvesync#140]
I just ordered the Levoit Dual 200 humidifier in spain and I get an error after adding Vesync integration in Home Assistant:

> 2022-07-11 18:48:58 WARNING (MainThread) [homeassistant.components.vesync.fan] Humidifier - Unknown device type - LUH-D301S-WEU
> 2022-07-11 18:49:27 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mymail@gmail.com for switch
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
> result = await component.async_unload_entry(hass, self)
> File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 87, in async_unload_entry
> return await component.async_unload_entry(entry)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
> raise ValueError("Config entry was never loaded!")
> ValueError: Config entry was never loaded!
> 2022-07-11 18:49:27 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mymail@gmail.com for light
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
> result = await component.async_unload_entry(hass, self)
> File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 603, in async_unload_entry
> return await component.async_unload_entry(entry)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
> raise ValueError("Config entry was never loaded!")
> ValueError: Config entry was never loaded!

**Comment by MickL** [comment]
It is already added, problem relies in Home Assistant integration
