### ISSUE TITLE
Support Levoit 6000S

### ISSUE THREAD

**Issue by bmos** [webdjoe/pyvesync#256]
I'd love it if this library could support the 6000S humidifier. Let me know if there is more info I can provide!

**Comment by bmos** [comment]
Here is some information from @echowarp.

> The device shows up in the logs, but there seems to be a python error when loading the config.
> 
> ```
> {
>   "home_assistant": {
>     "installation_type": "Home Assistant OS",
>     "version": "2024.11.1",
>     "dev": false,
>     "hassio": true,
>     "virtualenv": false,
>     "python_version": "3.12.4",
>     "docker": true,
>     "arch": "x86_64",
>     "timezone": "America/Chicago",
>     "os_name": "Linux",
>     "os_version": "6.6.54-haos",
>     "supervisor": "2024.11.2",
>     "host_os": "Home Assistant OS 13.2",
>     "docker_version": "27.2.0",
>     "chassis": "vm",
>     "run_as_root": true
>   },
>   "custom_components": {},
>   "integration_manifest": {
>     "domain": "vesync",
>     "name": "VeSync",
>     "codeowners": [
>       "markperdue",
>       "webdjoe",
>       "thegardenmonkey",
>       "cdnninja"
>     ],
>     "config_flow": true,
>     "documentation": "https://www.home-assistant.io/integrations/vesync",
>     "iot_class": "cloud_polling",
>     "loggers": [
>       "pyvesync"
>     ],
>     "requirements": [
>       "pyvesync==2.1.12"
>     ],
>     "is_built_in": true,
>     "overwrites_built_in": false
>   },
>   "setup_times": {
>     "null": {
>       "setup": 1.5821075066924095e-05
>     },
>     "**REDACTED**": {
>       "wait_import_platforms": -0.0026208481285721064,
>       "config_entry_setup": 0.7598381408024579
>     }
>   },
>   "data": {
>     "vesync": {
>       "bulb_count": 0,
>       "fan_count": 1,
>       "outlets_count": 0,
>       "switch_count": 0,
>       "timezone": "America/Chicago"
>     },
>     "devices": {
>       "bulbs": [],
>       "fans": [
>         {
>           "manager": "**REDACTED**",
>           "device_name": "Superior 6000S Smart Evaporative Humidifier",
>           "device_image": "https://image.vesync.com/defaultImages/LEH-S601S-WUS/icon_LEH_S601S_WUS_240.png",
>           "cid": "***REDACTED***",
>           "connection_status": "online",
>           "connection_type": "WiFi+BTOnboarding+BTNotify",
>           "device_type": "LEH-S601S-WUS",
>           "type": "wifi-air",
>           "uuid": "**REDACTED**",
>           "config_module": "VS_WFON_AHM_LEH-S601S-WUS_US",
>           "mac_id": "**REDACTED**",
>           "mode": "humidity",
>           "speed": null,
>           "extension": null,
>           "current_firm_version": null,
>           "device_region": "US",
>           "pid": null,
>           "sub_device_no": null,
>           "config": {},
>           "device_status": "off",
>           "_config_dict": {
>             "module": "VeSyncSuperior6000S",
>             "models": [
>               "LEH-S601S-WUS"
>             ],
>             "features": [],
>             "mist_modes": [
>               "auto",
>               "humidity",
>               "sleep",
>               "manual"
>             ],
>             "mist_levels": [
>               1,
>               2,
>               3,
>               4,
>               5,
>               6,
>               7,
>               8,
>               9
>             ]
>           },
>           "mist_levels": [
>             1,
>             2,
>             3,
>             4,
>             5,
>             6,
>             7,
>             8,
>             9
>           ],
>           "mist_modes": [
>             "auto",
>             "humidity",
>             "sleep",
>             "manual"
>           ],
>           "details": {
>             "humidity": 55,
>             "target_humidity": 60,
>             "mist_virtual_level": 0,
>             "mist_level": 0,
>             "water_lacks": 0,
>             "water_tank_lifted": 0,
>             "filter_life_percentage": 96,
>             "temperature": 680,
>             "display": 1,
>             "drying_mode": {
>               "dryingLevel": 1,
>               "autoDryingSwitch": 1,
>               "dryingState": 1,
>               "dryingRemain": 7163
>             }
>           },
>           "_api_modes": [
>             "getHumidifierStatus",
>             "setSwitch",
>             "setVirtualLevel",
>             "setTargetHumidity",
>             "setHumidityMode",
>             "setDisplay",
>             "setDryingMode"
>           ]
>         }
>       ],
>       "outlets": [],
>       "switches": []
>     }
>   }
> }
> ```
> 
> ```
> 2024-11-09 10:35:23.927 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.10'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 
> 2024-11-09 10:36:22.392 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry ***REDACTEDEMAILADDRESS*** for light
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
>     result = await component.async_unload_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 680, in async_unload_entry
>     return await hass.data[DATA_COMPONENT].async_unload_entry(entry)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in async_unload_entry
>     raise ValueError("Config entry was never loaded!")
> ValueError: Config entry was never loaded!
> ```

**Comment by bmos** [comment]
I see the code does have some information about this model, but it's not included in the list of supported models...
https://github.com/webdjoe/pyvesync/blob/master/src/pyvesync/vesyncfan.py#L74-L80

**Comment by webdjoe** [comment]
What is the device info that is printed to log when running the library?

**Comment by bmos** [comment]
Is this what you want?
Interestingly it seems the model code for this is S601S although it is marketed as S6000.

```
2024-12-04 09:45:59,726 - DEBUG - New device list initialized
2024-12-04 09:45:59,726 - DEBUG - Start updating the device details one by one
2024-12-04 09:45:59,727 - DEBUG - =======call_api=============================
2024-12-04 09:45:59,727 - DEBUG - [post] calling '/cloud/v2/deviceManaged/bypassV2' api
2024-12-04 09:45:59,727 - DEBUG - API call URL: 
  https://smartapi.vesync.com/cloud/v2/deviceManaged/bypassV2
2024-12-04 09:45:59,727 - DEBUG - API call headers: 
  {
  "Content-Type": "application/json; charset=UTF-8",
  "User-Agent": "okhttp/3.12.1"
}
2024-12-04 09:45:59,727 - DEBUG - API call json: 
  {
  "timeZone": "America/New_York",
  "acceptLanguage": "en",
  "accountID": "##_REDACTED_##",
  "token": "##_REDACTED_##",
  "appVersion": "2.8.6",
  "phoneBrand": "SM N9005",
  "phoneOS": "Android",
  "traceId": "1733323559",
  "method": "bypassV2",
  "debugMode": false,
  "deviceRegion": "US",
  "cid": "##_REDACTED_##",
  "configModule": "VS_WFON_AHM_LEH-S601S-WUS_US",
  "payload": {
    "method": "getHumidifierStatus",
    "source": "APP",
    "data": {}
  }
}
2024-12-04 09:46:00,102 - DEBUG - API response: 

  {
  "traceId": "1733323559",
  "code": 0,
  "msg": "request success",
  "module": null,
  "stacktrace": null,
  "result": {
    "traceId": "1733323559",
    "code": 0,
    "result": {
      "powerSwitch": 1,
      "humidity": 42,
      "targetHumidity": 48,
      "virtualLevel": 5,
      "mistLevel": 2,
      "workMode": "humidity",
      "waterLacksState": 0,
      "waterTankLifted": 0,
      "autoStopSwitch": 1,
      "autoStopState": 0,
      "screenSwitch": 1,
      "screenState": 1,
      "scheduleCount": 0,
      "timerRemain": 0,
      "errorCode": 0,
      "autoPreference": 1,
      "childLockSwitch": 0,
      "filterLifePercent": 90,
      "temperature": 662,
      "maxLevelNotify": 0,
      "waterShortageDryingSwitch": 1,
      "humidityPreference": 1,
      "dryingMode": {
        "dryingLevel": 1,
        "autoDryingSwitch": 1,
        "dryingState": 2,
        "dryingRemain": 7200
      },
      "isSupportSensor": 1,
      "sensorContent": {
        "sensorStatus": "noDevices"
      },
      "waterPump": {
        "cleanStatus": 0,
        "remainTime": 0,
        "totalTime": 65
      }
    }
  }
} 
 
2024-12-04 09:46:00,102 - DEBUG - No configuration found in humidifier status
```

**Comment by bmos** [comment]
If you need me to map out different modes and states I can do that, but hopefully it follows the patterns of other units enough to get it going and I can just map out what's missing.

**Comment by webdjoe** [comment]
Thank you! It would be very helpful if you could show the status response
with different states and describe the state of the features. It seems like
this device has a lot of features

**Comment by bmos** [comment]
Looks like someone is already working on this

https://github.com/micahqcade/custom_vesync/pull/11

**Comment by webdjoe** [comment]
It looks like the pyvesync library supports it, are you referring to the HA integration?

**Comment by bmos** [comment]
Is it just missing from the list of supported models? 

I saw "no configuration found in humidifier status" and that the model isn't listed and assumed this meamt it was not supported.

**Comment by webdjoe** [comment]
Can you post the exact log entries that are showing the error?

**Comment by webdjoe** [comment]
Closing this, please reopen and post logs if this is still an issue
