### ISSUE TITLE
Device update crash for 

### ISSUE THREAD

**Issue by rzolau** [webdjoe/pyvesync#39]
The following code causes crash on `dev.update` with `pyvesync 1.0.11` installed via `pip`:
```
#!/usr/bin/env python

from pyvesync import VeSync
import time

dev = VeSync(ID, PASS)
dev.login()

while True:
  dev.update()
  for d in dev.fans:
    print(d.device_name, d.air_quality, d.fan_level)
  time.sleep(60)
```
with the following output:
```
Traceback (most recent call last):
  File "./pyvesync-test.py", line 10, in <module>
    dev.update()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 245, in update
    outlets, switches, fans, bulbs = self.get_devices()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 192, in get_devices
    device_list)
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 139, in process_devices
    logger.debug('Fans Updated - ' + dev)
TypeError: can only concatenate str (not "VeSyncAir131") to str
```

**Comment by webdjoe** [comment]
That is fixed that in the next release https://github.com/markperdue/pyvesync/pull/38, it should have be `logger.debug('Fans Updated - ' + str(dev))`

**Comment by rzolau** [comment]
Awesome
