### ISSUE TITLE
Property "dimmable" does not exist in the feature_dict

### ISSUE THREAD

**Issue by HyperCharlie** [webdjoe/pyvesync#65]
I am using the Etekcity adapter for the Webthings Gateway, and yesterday(ish) it stopped functioning, with a bunch of errors that are similar to this:

2020-12-20 19:37:15.045 INFO   : Loading add-on: etekcity-adapter
2020-12-20 19:37:21.633 ERROR  : etekcity-adapter: Traceback (most recent call last):
2020-12-20 19:37:21.636 ERROR  : etekcity-adapter:   File "/home/pi/.webthings/addons/etekcity-adapter/main.py", line 31, in <module>
2020-12-20 19:37:21.639 ERROR  : etekcity-adapter:     _ADAPTER = EtekcityAdapter(verbose=_DEBUG)
2020-12-20 19:37:21.642 ERROR  : etekcity-adapter:   File "/home/pi/.webthings/addons/etekcity-adapter/pkg/etekcity_adapter.py", line 41, in __init__
2020-12-20 19:37:21.645 ERROR  : etekcity-adapter:     self.start_pairing(_TIMEOUT)
2020-12-20 19:37:21.648 ERROR  : etekcity-adapter:   File "/home/pi/.webthings/addons/etekcity-adapter/pkg/etekcity_adapter.py", line 71, in start_pairing
2020-12-20 19:37:21.650 ERROR  : etekcity-adapter:     device = EtekcitySwitch(self, _id, dev)
2020-12-20 19:37:21.653 ERROR  : etekcity-adapter:   File "/home/pi/.webthings/addons/etekcity-adapter/pkg/etekcity_device.py", line 207, in __init__
2020-12-20 19:37:21.655 ERROR  : etekcity-adapter:     if vesync_dev.is_dimmable():
2020-12-20 19:37:21.658 ERROR  : etekcity-adapter:   File "/home/pi/.webthings/addons/etekcity-adapter/lib/pyvesync/vesyncswitch.py", line 29, in is_dimmable
2020-12-20 19:37:21.661 ERROR  : etekcity-adapter:     if 'dimmable' in feature_dict.get(self.device_type):
2020-12-20 19:37:21.664 ERROR  : etekcity-adapter: TypeError: argument of type 'NoneType' is not iterable

I originally reported the error in the adapter's repository, but the maintainer there recommended I report it here because the error is coming from inside of the pyvesync module and the adapter had not updated. Is it possible that something has changed in the etekcity API?

**Comment by webdjoe** [comment]
What device are you using?

**Comment by HyperCharlie** [comment]
I'm using the etekcity smart switch (non dimmers), https://www.etekcity.com/product/100442

**Comment by HyperCharlie** [comment]
Any chance of having a look at this? Thanks!

**Comment by HyperCharlie** [comment]
I just confirmed that I have ESWL01 switches, which are on the supported list.

**Comment by webdjoe** [comment]
I know what is going on, I thought I had corrected this previously. I submit a PR to correct shortly.

**Comment by webdjoe** [comment]
Just posted a response here https://github.com/WebThingsIO/etekcity-adapter/issues/8#issuecomment-757052695

This is fully working on my end, it is an issue with the adapter

**Comment by HyperCharlie** [comment]
Thank you @webdjoe
