### ISSUE TITLE
HTTPSConnectionPool: Read timed out leads to AttributeError in get_details

### ISSUE THREAD

**Issue by provinzio** [webdjoe/pyvesync#80]
I am using pyvesync in an home assisstant integration. I am regularly seeing following in my log file and assume that it's an bug in `pyvesync`.

```
2021-05-06 13:31:24 WARNING (SyncWorker_3) [pyvesync.helpers] HTTPSConnectionPool(host='smartapi.vesync.com', port=443): Read timed out. (read timeout=5)
2021-05-06 13:31:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for humidifier.lufti fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 490, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vesync/common.py", line 89, in update
    self.device.update()
  File "/usr/local/lib/python3.8/site-packages/pyvesync/vesyncfan.py", line 364, in update
    self.get_details()
  File "/usr/local/lib/python3.8/site-packages/pyvesync/vesyncfan.py", line 345, in get_details
    outer_result = r.get('result', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by webdjoe** [comment]
#83

**Comment by webdjoe** [comment]
#83 API Return Error - Same issues being discussed here.
